#PyTorch


Длабокото учење (Deep Learning) всушност се заснова на пресметка на тензори (tensors), кои претставуваат генерализации на матрица што може да се индексира во повеќе од две димензии.

Најпрво да ја погледнеме torch библиотеката. Оваа библиотека е open-source ML библиотека која нуди мноштво на алгоритми за длабоко учење.

Можеме да ја импортираме на следниот начин.

In [ ]:
import torch

torch.manual_seed(1)

Следно, ќе пробаме да искористиме GPU.

In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

Што претставува еден 3D тензор? 

Да го погледнеме ова: 

*   Ако имаме вектор, индексирањето во векторот ни дава скалар.
*   Ако имаме матрица, индексирањето во матрицата ни дава вектор.
*   Ако имаме 3D тензор, тогаш индексирањето во тензорот ни дава матрица.

In [ ]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
data = [0., 1., 2.]
vector = torch.tensor(data)
print(vector)

# Creates a matrix'
data = [[0., 1., 2.], [0., 1., 2.]]
matrix = torch.tensor(data)
print(matrix)

# Create a 3D tensor of size 2x2x2.
data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
tensor = torch.tensor(data)
print(tensor)

tensor([0., 1., 2.])
tensor([[0., 1., 2.],
        [0., 1., 2.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [ ]:
# Index into V and get a scalar (0 dimensional tensor)
print(vector[0])
# Get a Python number from it
print(vector[0].item())

# Index into M and get a vector
print(matrix[0])

# Index into T and get a matrix
print(tensor[0])

tensor(0.)
0.0
tensor([0., 1., 2.])
tensor([[1., 2.],
        [3., 4.]])


Еден тензор ги има следните атрибути.

In [ ]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


За да можеме да го промениме обликот на одреден тензор го користиме view() методот, кој се користи често за да одговориме на побарувањата на одредена невронска мрежа или модел.

За да го покажеме ова креираме рандом тензор.

In [ ]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095],
         [-0.1002, -0.6092, -0.9798, -1.6091],
         [ 0.4391,  1.1712,  1.7674, -0.0954]],

        [[ 0.1394, -1.5785, -0.3206, -0.2993],
         [-0.7984,  0.3357,  0.2753,  1.7163],
         [-0.0561,  0.9107, -1.3924,  2.6891]]])
tensor([[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002, -0.6092, -0.9798, -1.6091,
          0.4391,  1.1712,  1.7674, -0.0954],
        [ 0.1394, -1.5785, -0.3206, -0.2993, -0.7984,  0.3357,  0.2753,  1.7163,
         -0.0561,  0.9107, -1.3924,  2.6891]])


Можеме да ги користиме тензорите и заедно со концептот на Computation Graphs за поголема ефикасност на задачите на длабокото учење.

Повеќе функционалности и начини на користење ќе видиме со самите модели во следните вежби.

# Едноставна употреба на претрениран модел за text -> speech на Англиски јазик

Постојат повеќе APIs кои може да ни помогнат да ја извршиме задачата на конвертирање на текст во говор во Python. Едно такво API е дадено од Google и е познато под името gTTS API.

Ова gTTS API поддржува повеќе јазици: Англиски, Хинду, Германски итн. 

Следува една пример употреба.

Најпрво го инсталираме gTTS.

In [ ]:
!pip install gTTS

Следен чекор е импорт на модулот кој ни е потребен за text -> speech конверзијата, специфицирање на јазикот, и дефинирање на текстот кој ќе го користиме.



In [ ]:
from gtts import gTTS
  
sample_text = 'This is exciting!'
  
language = 'en'

Понатаму, ги даваме текстот и избраниот јазик на engine, специфирајќи го атрибутот slow да биде False, за да аудиото кое се добива има голема брзина.

Го зачувуваме аудио фајлот.

In [ ]:
obj = gTTS(text=sample_text, lang=language, slow=False)
obj.save("first.mp3")

Можете да го симнете фајлот и истиот да го преслушате, како и да го пробате со повеќе различни текстови.

Со тоа успешно се запознавме со основите за ХПЦ библиотките за работа!